### PR TITLE
Overall update and Implement Config Flow

### LINKED ISSUE #17: Is this integration dead?
I would really like to include my Freeze and Water sensors into this service.  It appears development on API v2 has stopped.  Is this integration dead and should Noonlight customers move to a different service?  Thanks

### LINKED ISSUE #18: Using Deprecated hass.helpers.dispatcher
Not sure if this is still being maintained, but this warning began with 2024.5. If not addressed by 2024.11, it looks like the integration will stop working.

@snicker I just noticed that you put out the last release. Any chance this could be updated? 

```
2024-05-05 11:07:48.165 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration noonlight which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-05 11:08:43.978 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'noonlight' accesses hass.helpers.dispatcher. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from dispatcher directly at custom_components/noonlight/switch.py, line 36: hass.helpers.dispatcher.async_dispatcher_connect(, please report it to the author of the 'noonlight' custom integration
```

### PR DESCRIPTION
**Pull request by Snuffy2**
Significant code update/upgrade.

* Linting with Black, iSort, etc.
* Updated hacs.json and manifest.json to be accurate/correct
* GitHub Actions to validate against hassfest and HACS requirements
* GitHub Actions to automatically set version and zip on release (must release using proper semantic versioning)
* Adds address information using the v1 API and gives user the option of sending Lat/Long or Address with the Alarm
* Add unique id to Switch
* Setup via Config Flow
    * Imports the existing YAML config and sets a Repair announcing YAML deprecation with HA 2025.1 (can change as desired)

Fixes #17
Fixes #18

### CODE REVIEW

**Comment by saxopwn** [comment]
@snicker - will this get merged before hass.helpers.dispatcher stops working in 2024.11?

**Comment by snicker** [comment]
> @snicker - will this get merged before hass.helpers.dispatcher stops working in 2024.11?

yes, aiming to have this merged in the next week

**Comment by snicker** [comment]
hey @Snuffy2  - I've been testing this PR this evening. Fresh bare install of Home Assistant 2024.10.1 (from the official docker image)

when configuring through the UI, the switch continues to show as unavailable. However, YAML configuration works. I've looked at logs and can't seem to figure out why this might be happening... do you have any ideas?

**Comment by Snuffy2** [comment]
Yeah I see what's going on. If you set it up and then restart HA it will work. It is because the initial token update trigger is on HA start and if you add it via the UI, the next time HA start will happen is on restart. 

It was how the previous version started the update and I missed it. Should be a simple change. I'll look when I'm at a computer.

**Comment by Snuffy2** [comment]
Ok, it should start correctly now.

**Comment by snicker** [comment]
thanks @Snuffy2 will test tomorrow!

**Comment by snicker** [comment]
all working great and tested!

@heythisisnate - recommending we merge and release as v1.2

**Review by heythisisnate — APPROVED** [review]

**Comment by heythisisnate** [comment]
@Snuffy2 thank you so much for your contribution!
@snicker appreciate you testing and reviewing this

**Comment by Snuffy2** [comment]
Great! Will you be putting this into a GitHib release?

**Comment by heythisisnate** [comment]
Yes I will do that now.

**Pull request merged**
